import type { Metadata } from 'next';
import './globals.css';
import iranSansXFaNum from '@/configuration/fonts/iranSansXFaNum';
import { ReactNode } from 'react';
// import { ThemeProvider } from '@/providers/theme-provider';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: ReactNode;
  authModal: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranSansXFaNum.className} ${iranSansXFaNum.variable}`}>
        {/* <ThemeProvider > */}
        <main style={{ height: '3000px' }}>
          {authModal}
          {children}
          <div id="portal-root" />
        </main>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}